# Generated by Django 3.0.3 on 2020-03-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='The is a test description about the product.'),
            preserve_default=False,
        ),
    ]
